name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Release, Debug]
        projects: [foo_cover_info, foo_cover_resizer, foo_run_main]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild /m '/p:Platform=Win32;Configuration=${{ matrix.configuration }}' ${{ matrix.projects }}\${{ matrix.projects }}.sln
